---
- name: Ensure pmm-data container exists
  docker_container:
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-data
    state: present
    volumes:
      - /srv
    command: /bin/true

- name: Ensure pmm-server container exists
  docker_container:
    env: "{{ pmm_server_docker_env }}"
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-server
    ports:
      - "{{ pmm_server_http_port }}:80"
      - "{{ pmm_server_https_port }}:443"
    restart_policy: "{{ pmm_server_restart_policy }}"
    state: started
    volumes_from:
      - pmm-data

- name: Disable Grafana auth
  shell: docker exec -t pmm-server sed -i '/# enable anonymous access/!b;n;cenabled = true' /etc/grafana/grafana.ini
  notify: restart pmm-server
  when: pmm_server_anonymous_access

- name: Disable QAN auth
  shell: docker exec -t pmm-server sed -i 's/auth_request \/auth_request;/# no auth_request/' /etc/nginx/conf.d/pmm.conf
  notify: restart pmm-server
  when: pmm_server_anonymous_access
