---
- name: Ensure pmm-data container exists
  docker_container:
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-data
    state: present
    volumes:
      - /srv
    command: /bin/true

- name: Ensure pmm-server container exists
  docker_container:
    env: "{{ pmm_server_docker_env }}"
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-server
    ports:
      - "{{ pmm_server_http_port }}:80"
      - "{{ pmm_server_https_port }}:443"
    restart_policy: "{{ pmm_server_restart_policy }}"
    state: started
    volumes_from:
      - pmm-data

- name: Enable Grafana anonymous access
  command: docker exec -t pmm-server sed -i '/# enable anonymous access/!{q100};b;n;cenabled = true' /etc/grafana/grafana.ini
  register: result
  changed_when: "result.rc != 100"
  failed_when: "result.rc != 0 and result.rc != 100"
  notify: restart pmm-server
  when: pmm_server_anonymous_access

- name: Disable auth at nginx level
  command: docker exec -t pmm-server sed -i '/auth_request \/auth_request;/!{q100};# no auth_request' /etc/nginx/conf.d/pmm.conf
  register: result
  changed_when: "result.rc != 100"
  failed_when: "result.rc != 0 and result.rc != 100"
  notify: restart pmm-server
  when: pmm_server_anonymous_access
