---
- name: Ensure pmm-data container exists
  docker_container:
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-data
    state: present
    volumes:
      - /srv
    command: /bin/true

- name: Ensure pmm-server container exists
  docker_container:
    env: "{{ pmm_server_docker_env }}"
    image: "{{ pmm_server_docker_image_name }}:{{ pmm_server_docker_image_version }}"
    name: pmm-server
    ports:
      - "{{ pmm_server_http_port }}:80"
      - "{{ pmm_server_https_port }}:443"
    restart_policy: "{{ pmm_server_restart_policy }}"
    state: started
    volumes_from:
      - pmm-data

- name: add pmm-server container to inventory
  add_host:
    name: pmm-server
    ansible_connection: docker
  changed_when: false
  when: pmm_server_anonymous_access

- name: Enable Grafana anonymous access
  replace:
    path: /etc/grafana/grafana.ini
    regexp: '(# enable anonymous access\nenabled = )false'
    replace: '\1true'
  delegate_to: pmm-server
  notify: restart pmm-server
  when: pmm_server_anonymous_access

- name: Disable auth at nginx level
  replace:
    path: /etc/nginx/conf.d/pmm.conf
    regexp: '^(\s*)auth_request \/auth_request;$'
    replace: '\1# no auth_request'
  delegate_to: pmm-server
  notify: restart pmm-server
  when: pmm_server_anonymous_access
